force-app/main/default/objects/Car_Type__c/Car_Type__c.object-meta.xml
<CustomObject>
    <label>CarType</label>
    <nameField>
        <label>CarType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CarTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car_Type__c/fields/Price_Day__c.field-meta.xml
<CustomField>
    <fullName>Price_Day__c</fullName>
    <label>Price Day</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Car_Type__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Coupe</fullName>
            </value>
            <value>
                <fullName>Crossover</fullName>
            </value>
            <value>
                <fullName>FullSize</fullName>
            </value>
            <value>
                <fullName>Hatchback</fullName>
            </value>
            <value>
                <fullName>MiniVan</fullName>
            </value>
            <value>
                <fullName>Sedan</fullName>
            </value>
            <value>
                <fullName>SUV</fullName>
            </value>
            <value>
                <fullName>Muscle Car</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CarTypeController.cls
public with sharing class CarTypeController {
    
    @AuraEnabled
    public static List<Car_Type__c> getTypes() {       
        try {
             return [SELECT Id, Name, Type__c, Price_Day__c
                         FROM Car_Type__c WITH SECURITY_ENFORCED ORDER BY Name  ];
    
        } catch (Exception e) {
            throw new AuraHandledException('Server-side Error: ' + e.getMessage());
        }

    }

}