force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Car Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chevrolet</fullName>
            </value>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
            <value>
                <fullName>KIA</fullName>
            </value>
            <value>
                <fullName>Lexus</fullName>
            </value>
            <value>
                <fullName>Toyota</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car__c/fields/CarType__c.field-meta.xml
<CustomField>
    <fullName>CarType__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>CarType</label>
    <referenceTo>Car_Type__c</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Brand__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Explorer</fullName>
            </value>
            <value>
                <fullName>Focus</fullName>
            </value>
            <value>
                <fullName>Camaro</fullName>
            </value>
            <value>
                <fullName>Impala</fullName>
            </value>
            <value>
                <fullName>Civic</fullName>
            </value>
            <value>
                <fullName>Accord</fullName>
            </value>
            <value>
                <fullName>Rav4</fullName>
            </value>
            <value>
                <fullName>Sienna</fullName>
            </value>
            <value>
                <fullName>Optima</fullName>
            </value>
            <value>
                <fullName>Telluride</fullName>
            </value>
            <value>
                <fullName>IS</fullName>
            </value>
            <value>
                <fullName>Lx</fullName>
            </value>
            <value>
                <fullName>CR-V</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car_Type__c/Car_Type__c.object-meta.xml
<CustomObject>
    <label>CarType</label>
    <nameField>
        <label>CarType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CarTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car_Type__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Coupe</fullName>
            </value>
            <value>
                <fullName>Crossover</fullName>
            </value>
            <value>
                <fullName>FullSize</fullName>
            </value>
            <value>
                <fullName>Hatchback</fullName>
            </value>
            <value>
                <fullName>MiniVan</fullName>
            </value>
            <value>
                <fullName>Sedan</fullName>
            </value>
            <value>
                <fullName>SUV</fullName>
            </value>
            <value>
                <fullName>Muscle Car</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CarController.cls
public with sharing class CarController {

    @AuraEnabled
    public static List<AggregateResult> getCars() {
        // Select list of cars grouped by brand, model, year, type to avoid unuseful duplicate results.  
        try { 
            
            List<AggregateResult> carlist = [SELECT  Brand__c, Model__c, Year__c, CarType__r.Type__c
        	FROM Car__c WITH SECURITY_ENFORCED 
                    GROUP BY Brand__c, Model__c, Year__c, CarType__r.Type__c 
                    ORDER BY Brand__c, Model__c , Year__c];

        	 return carlist;  
            
        } catch (Exception e) {
            throw new AuraHandledException('Server-side Error: ' + e.getMessage());
        }
                       
    }
        

}